### ISSUE TITLE
draft -23 section 7.7 route reflector procedural changes

### ISSUE THREAD

**Issue by jhaas-pfrc** [ietf-wg-idr/draft-ietf-idr-bgp-ct#60]
[This keeps getting mentioned, but due to lack of an issue has kept on getting dropped.]

Section 7.7 is a backdoor attempt to change BGP route reflection procedures.

While the procedural change may be desirable, the -ct document may not be appropriate to do so.

**Comment by jhaas-pfrc** [comment]
Note that the need for the discussion is motivated by scenarios such that route reflectors reset the next hop and force themselves to be in the forwarding path.  This is not the general use case scenario for route reflection.

**Comment by kalirajv** [comment]
Jeff, we can separate it out to a separate draft, if Chairs see that as the best option.

I have been pondering over a few procedural questions, because of which I have been reluctant to take that step:

- will the new draft remain WG adopted (e.g., draft-ietf-idr-bgp-pathsel-fwd-rr)?
- will it go thru Last Call along with draft-ct? 
- will the new draft be a Standards document or will be Experimental as-well?
- will the reference in draft-ct to the new draft be Normative or Informative? I think it would be Normative. Will that cause any issues with missed-refs? 

Can the Chairs clarify on these questions? accordingly I can start working on it.

The 'RR with nexthop-self' is an important required scenario in BGP-LU or BGP-CT ABR deployments. So I think we should put a reference to the text in draft-ct 7.7, even if separated  out to a new draft.

**Comment by suehares** [comment]
Kaliraj:

On your questions, Keyur and I have noted about this section.


  1.  Can you separate it out as a separate document – You should.

Let me see the text.  Let’s start with the document being a WG document.

It inherits the same status of Experimental, but it can be moved from experimental as an individual document.



  1.  Does it need to go through WG LC with the draft-ietf-idr-bgp-ct and draft-ietf-idr-bgp-ct-srv6


I do not see why this section needs to be normative instead of informative.  Let’s chat about this fact on Monday.
                If it is informative, there is no problem with misref.
                If it is normative, then misref can occur.


  1.  As stated above, it start with experimental as a split.  It can go to proposed if the WG agrees.
  2.   See my comments above – I think informative.  If Jeff has time, we’ll chat together.

Sue

**Comment by suehares** [comment]
Closed - with the creation of draft-ietf-idr-bgp-fwd-rr-01. 

A new repository will be entered for this document.,

**Comment by suehares** [comment]
Closed - with the creation of draft-ietf-idr-bgp-fwd-rr-01. 

A new repository will be entered for this document
